CREATE TABLE SUMA_DIGITOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    N1 NUMBER,
    N2 NUMBER,
    N3 NUMBER,
    N4 NUMBER,
    N5 NUMBER,
    N6 NUMBER,
    N7 NUMBER,
    N8 NUMBER,
    RESULTADO NUMBER,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

CREATE OR REPLACE PROCEDURE SP_GUARDAR_SUMA (
    P_N1 IN NUMBER,
    P_N2 IN NUMBER,
    P_N3 IN NUMBER,
    P_N4 IN NUMBER,
    P_N5 IN NUMBER,
    P_N6 IN NUMBER,
    P_N7 IN NUMBER,
    P_N8 IN NUMBER,
    P_RESULTADO IN NUMBER
) AS
BEGIN
    INSERT INTO SUMA_DIGITOS (
        N1, N2, N3, N4, N5, N6, N7, N8, RESULTADO
    ) VALUES (
        P_N1, P_N2, P_N3, P_N4, P_N5, P_N6, P_N7, P_N8, P_RESULTADO
    );
    COMMIT;
END;
/

COMMIT;